name: booba2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2


  flutter:
    sdk: flutter
  
  # Firebase 
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_firestore: ^0.0.3+1
  
  # Statemanagement, navigation, helpers and more
  get: ^4.6.1

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
